language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - "git config --global user.email 'nobody@loslassa.com'"
  - "git config --global user.name 'Loslassa Tester'"
install:
  - "pip install coveralls"
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
script: "py.test --cov=loslassa tests"
after_success:
  coveralls
